export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const EDIT_USER = 'EDIT_USER';
export const UNREGISTER = 'UNREGISTER';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const AUTH_LOADING = 'AUTH_LOADING';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_CONFIRM = 'RESET_PASSWORD_CONFIRM';
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED';

export const FOLLOW_LOADING = 'FOLLOW_LOADING';
export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';
export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const GET_FOLLOWINGS = 'GET_FOLLOWINGS';
export const GET_USER_FOLLOWINGS = 'GET_USER_FOLLOWINGS';

export const POST_LOADING = 'POST_LOADING';
export const GET_MY_FEED = 'GET_MY_FEED';
export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const POST_ERROR = 'POST_ERROR';

export const PROFILE_LOADING = 'PROFILE_LOADING';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_ERROR = 'PROFILE_ERROR';
